// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZlh2DyTjJM0vDJOKardzyBi7l74Mmns',
    appId: '1:130370890375:web:713eb51d43a9ad58d52622',
    messagingSenderId: '130370890375',
    projectId: 'budget-tracking-a7f81',
    authDomain: 'budget-tracking-a7f81.firebaseapp.com',
    storageBucket: 'budget-tracking-a7f81.appspot.com',
    measurementId: 'G-ES2LSX0PQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAND0zyEnh7_sOYJjZ_6UHw4_0zZZcdN_k',
    appId: '1:130370890375:android:b7ed22083ab3f581d52622',
    messagingSenderId: '130370890375',
    projectId: 'budget-tracking-a7f81',
    storageBucket: 'budget-tracking-a7f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ8p4Asw5TjU3F5arUaKBfbVDtAQpJPz8',
    appId: '1:130370890375:ios:0282b380be905f17d52622',
    messagingSenderId: '130370890375',
    projectId: 'budget-tracking-a7f81',
    storageBucket: 'budget-tracking-a7f81.appspot.com',
    iosClientId: '130370890375-866i5gefb36v792vp81i1gh754cjqsr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ8p4Asw5TjU3F5arUaKBfbVDtAQpJPz8',
    appId: '1:130370890375:ios:4ae96888db5fcca0d52622',
    messagingSenderId: '130370890375',
    projectId: 'budget-tracking-a7f81',
    storageBucket: 'budget-tracking-a7f81.appspot.com',
    iosClientId: '130370890375-h4ifaog0s764d40rf7eul93cg9vuvicb.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetTracking.RunnerTests',
  );
}
